---
  - name: playbook1
    hosts: webservers
    gather_facts: no
    tasks: 
      - name: install httpd package
        dnf: 
          name: httpd
          state: latest
      - name: start httpd service
        service:
          name: httpd
          state: started
      - name: add http role to firewalld
        firewalld:
          service: http
          permanent: true
          state: enabled
      - name: reload firewalld service
        service:
          name: firewalld
          state: reloaded
